name: C++ CI with Tests  # Назва workflow

on:  # Запускати на:
  push:  # Кожному пуші
    branches: [ main ]
  pull_request:  # Кожному PR
    branches: [ main ]

jobs:  # Роботи (завдання)
  build-and-test:  # Назва job
    runs-on: ubuntu-latest  # На Linux-машині (безкоштовно)

    steps:
    - name: Checkout code  # Клонуємо репозиторій
      uses: actions/checkout@v4  # Офіційний action

    - name: Install dependencies  # Встановлюємо Google Test
      run: |
        sudo apt update
        sudo apt install -y libgtest-dev cmake build-essential

    - name: Configure CMake  # Конфігуруємо проєкт
      run: cmake -B build -S .  # Створюємо папку build

    - name: Build project  # Компілюємо
      run: cmake --build build --config Debug  # Debug для тестів

    - name: Run tests  # Запускаємо unit-тести
      run: ctest -V --test-dir build  # ctest з Google Test

    - name: Upload test results  # Опціонально: Зберігаємо результати (як артефакт)
      if: always()  # Навіть якщо тесті провалилися
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: build/Testing/
